/* Получение */
const SEND_AGENT_DATA = "SEND_AGENT_DATA";
const SEND_AGENT_DATA_SUCCESS = "SEND_AGENT_DATA_SUCCESS";
const SEND_AGENT_DATA_FAILED = "SEND_AGENT_DATA_FAILED";

export default {
  SEND_AGENT_DATA,
  SEND_AGENT_DATA_SUCCESS,
  SEND_AGENT_DATA_FAILED
};
